<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="robot_core" params="prefix">

        <!-- Example link -->
        <xacro:include filename="inertial_macros.xacro"/>


        <xacro:property name="rad_w" value="${0.042/2}"/>
        <xacro:property name="le_w" value="0.019"/>
        <xacro:property name="ly" value="0.12766"/>
        <xacro:property name="lx" value="0.18"/>
        <xacro:property name="lz" value="0.0569"/>

        <xacro:property name="off_lower_wcenter" value="0.013904"/>
        <xacro:property name="wheel_position" value="0.055340"/>
        <xacro:property name="caster_r" value="0.009525"/>

        <xacro:property name="ultra_x" value="0.003"/>
        <xacro:property name="ultra_y" value="0.08"/>
        <xacro:property name="ultra_z" value="0.02"/>


        <xacro:property name="imu_x_size" value="0.025"/>
        <xacro:property name="imu_y_size" value="0.02"/>
        <xacro:property name="imu_z_size" value="0.01"/>

        <xacro:property name="imu_pos_x" value="0.09"/>
        <xacro:property name="imu_pos_y" value="0.0"/>
        <xacro:property name="imu_pos_z" value="${imu_z_size/2}"/>
        


        <!-- Example link -->
        <link name="${prefix}base_link">
        </link>

        <joint name="${prefix}base_link" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}chassis"/>
            <origin xyz="-${wheel_position} 0 0"/>    
        </joint>

        <!-- chassis link -->
        <link name="${prefix}chassis">
            <visual>
                <origin xyz="${lx/2} 0 ${lz/2}"/>
                <geometry>
                    <box size="${lx} ${ly} ${lz}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="${lx/2} 0 ${lz/2}"/>
                <geometry>
                <box size="${lx} ${ly} ${lz}"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.5" x="${lx}" y="${ly}" z="${lz}">
                <origin xyz="${lx/2} 0 ${lz/2}" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>
        
        <!-- Ultrasonic sensor joint -->
        <joint name="${prefix}chassis_ultrasonic_joint" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}ultrasonic"/>
            <origin xyz="${lx/2+(lx/2 - wheel_position)} 0 ${lz}" rpy="0 0 0"/>    
        </joint>

        <!-- Ultrasonic sensor link -->
        <link name="${prefix}ultrasonic">
            <visual>
                <origin xyz="${ultra_x/2} 0 -${ultra_z/2}"/>
                <geometry>
                    <box size="${ultra_x} ${ultra_y} ${ultra_z}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="${ultra_x/2} 0 -${ultra_z/2}"/>
                <geometry>
                    <box size="${ultra_x} ${ultra_y} ${ultra_z}"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.05" x="${ultra_x}" y="${ultra_y}" z="${ultra_z}">
                <origin xyz="${ultra_x/2} 0 ${ultra_z/2}" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>



        <!-- left wheel joint -->
        <joint name="${prefix}left_wheel_joint" type="continuous">
            <parent link="${prefix}chassis"/>
            <child link="${prefix}left_wheel"/>
            <origin xyz="${wheel_position} ${ly/2+le_w/2} ${off_lower_wcenter}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>    
        </joint>

        <!-- left wheel link -->
        <link name="${prefix}left_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${rad_w}" length="${le_w}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${rad_w}" length="${le_w}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.1" length="${le_w}" radius="${rad_w}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <!-- right wheel joint -->
        <joint name="${prefix}right_wheel_joint" type="continuous">
            <parent link="${prefix}chassis"/>
            <child link="${prefix}right_wheel"/>
            <origin xyz="${wheel_position} -${ly/2+le_w/2} ${off_lower_wcenter}" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 -1"/>    
        </joint>

        <!-- right wheel link -->
        <link name="${prefix}right_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${rad_w}" length="${le_w}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${rad_w}" length="${le_w}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.1" length="${le_w}" radius="${rad_w}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <!-- caster wheel joint -->
        <joint name="${prefix}caster_wheel_joint" type="fixed">
            <parent link="${prefix}chassis"/>
            <child link="${prefix}caster_wheel"/>
            <origin xyz="${lx-caster_r} 0 0"/>  
        </joint>

        <!-- left wheel link -->
        <link name="${prefix}caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="${caster_r}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="0.1" radius="0.05">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <joint name="${prefix}base_imu_joint" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}imu_link"/>
            <origin xyz="${imu_pos_x} ${imu_pos_y} ${imu_pos_z}" rpy="0 0 0"/> 
        </joint>

        <link name="${prefix}imu_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${imu_x_size} ${imu_y_size} ${imu_z_size}"/>
                </geometry>
                <material name="red"/> 
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${imu_x_size} ${imu_y_size} ${imu_z_size}"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="0.01" x="${imu_x_size}" y="${imu_y_size}" z="${imu_z_size}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>

    </xacro:macro>
</robot>